config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/contact'
  get 'home/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" media="all" href="/assets/rails_admin/rails_admin.self-c883efa876e5a963fa352297089099b024aca40fa985ccc7cd58dbfa9948f59b.css?body=1" />
  </head>
  <header>
    <!-- Fixed navbar -->
    <nav id="fontNavBar" class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brandx" href="#">MeditArte</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'home', home_index_path %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <body>
    <div id="rown" class="container">

      <main>
        <div class="container">
          <div class="row">
            <form id="contact" class="col s12">
              <div class="row">
                <div class="input-field col s12">
                   <i class="material-icons prefix"></i>
                  <input id="first_name" type="text" class="validate">
                  <label class="contact-text"  for="first_name">Name</label>
                </div>
              </div>

              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix"></i>
                  <input id="last_name" type="text" class="validate">
                  <label class="contact-text" for="last_name">Phone</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix"></i>
                  <input id="email" type="email" class="validate">
                  <label class="contact-text" for="email" data-error="wrong" data-success="right">Email</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix"></i>
                  <textarea id="textarea1" class="materialize-textarea"></textarea>
                  <label class="contact-text" for="textarea1">Insert text</label>
                </div>
              </div>
              <center><button class="btn waves-effect waves-light">Enviar --> </button></center>
            </form>
          </div>
        </div>
      </main>
    </div>
  </body>
  <footer class="footer">
    <div class="container_footer">
      <span class="text-muted">&copy; Copyright 2018 - Development Tonny Brito</span><br>
      <span class="text-muted"><img class="flag" src="https://lipis.github.io/flag-icon-css/flags/4x3/br.svg" alt="Brazil Flag">  Devlandia - Curitiba - Br  <img class="flag" src="https://lipis.github.io/flag-icon-css/flags/4x3/br.svg" alt="Brazil Flag"></span>
    </div>
  </footer>
</html>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" media="all" href="/assets/rails_admin/rails_admin.self-c883efa876e5a963fa352297089099b024aca40fa985ccc7cd58dbfa9948f59b.css?body=1" />
  </head>
  <header>
    <!-- Fixed navbar -->
    <nav id="fontNavBar" class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brandx" href="#">MeditArte</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" <%= link_to 'Contact', home_contact_path %>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <body>
    <div id="rown" class="container">

      <main>
        <div class="container">
          <div class="row">
            <div id="left" class="col s6">


              <ul id="album">
                 <span id="text-family">Nossos Produtos </span><br><br>
                <a href="youandme.html"><li id="photo02"><span  class="test">Pingentes / Aneis</span></li></a>
                <a href="travelsint.html"><li id="photo01"><span>Brincos / Tornozeleiras</span></li></a>
                <a href="travelsnac.html"><li id="photo04"><span>Outros Produtos</span></li></a>
                <a href="wechildren.html"><li id="photo03"><span>Conjuntos</span></li></a>

              </ul>
            </div>


            <div id="right" class="col s6">
              <p class="title-history">Ipanema Beach 1983
              aqui começa uma nova historia
              </p>
              <p>
                Tonny Brito: Pescador<br>
                Ana Suely: Professora<br><br>
                Ele -> Natural de Lourenço Marques – Moçambique - Africa<br>
                Ela -> Patural de Paranaguá – Paraná – Brasil
              </p>
              <p>
                Se conheceram no inicio de 1983 na pequena escola 31 de março em Ipanema, namoraram por 7 meses, casaram-se em 12/12/1983.<br>
                Tiveram 3 filhos:
              </p>
              <p>
                Fellipe Eduardo – Kassya Karolina – Camilla Crystina
              </p>
              <p>
                Moraram em Ipanema ate 1995 quando tiveram que ir para Paranagua, pois seu filho mais velho precisava estudar, e na praia não tinha ensino fundamental.
                Em paranagua ficaram ate 2005, quando decidiram ir morar em Curitiba, ondem estão ate hoje.
              </p>
              <p>
                34 anos de casamento uma vida com altos e baixos, mas muito feliz...
              </p>

            </div>
          </div>
        </div>
      </main>

    </div>
  </body>
  <footer class="footer">
    <container_footer>
      <span class="text-muted">&copy; Copyright 2018 - Development Tonny Brito</span><br>
      <span class="text-muted"><img class="flag" src="https://lipis.github.io/flag-icon-css/flags/4x3/br.svg" alt="Brazil Flag"> Devlandia - Curitiba - Br <img class="flag" src="https://lipis.github.io/flag-icon-css/flags/4x3/br.svg" alt="Brazil Flag"></span>
    </container>
  </footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='IE=edge' http-equiv='X-UA-Compatible'>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
    <meta content='width=device-width, initial-scale=1' name='viewport; charset=utf-8'>
    <meta content='NONE,NOARCHIVE' name='robots'>
    <meta name="csrf-param" content="authenticity_token" />
    <script src="/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1"></script>
    <title>MeditArte</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>